### PR TITLE
refactoring redux

### PR DESCRIPTION
**Pull request by sonokougg**
I changed redux file structure using in #1 
After merge this PR, I gonna close #1

---
This change is [Reviewable](https://reviewable.io/reviews/tigerscave/sono-redux-counter/2)

### CODE REVIEW

**Review by zigen — CHANGES_REQUESTED** [review]
> Reviewed 4 of 12 files at r1, 10 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/tigerscave/sono-redux-counter/2)* status: all files reviewed, 3 unresolved discussions (waiting on @sonokou1109)

___
*[src/index.js, line 19 at r2](https://reviewable.io/reviews/tigerscave/sono-redux-counter/2#-LIv3AtQ3oaaEhPLvim7:-LIv3AtQ3oaaEhPLvim8:b7kypa8) ([raw file](https://github.com/tigerscave/sono-redux-counter/blob/5dfeb0804dee5ea995a7000b98a2c2023bc5efd5/src/index.js#L19)):*
> ```JavaScript
>   document.getElementById('root'),
> );
> registerServiceWorker();
> ```

what's this? do you really need this?
___
*[src/registerServiceWorker.js, line 1 at r2](https://reviewable.io/reviews/tigerscave/sono-redux-counter/2#-LIv3Gpy6tfdA24nZKpX:-LIv3Gpy6tfdA24nZKpY:beaycdj) ([raw file](https://github.com/tigerscave/sono-redux-counter/blob/5dfeb0804dee5ea995a7000b98a2c2023bc5efd5/src/registerServiceWorker.js#L1)):*
> ```JavaScript
> /* eslint-disable */
> ```

do you use this file?
It's better to delete this needless file rather than put `eslint-disable`, 
___
*[src/redux/createStore.js, line 8 at r2](https://reviewable.io/reviews/tigerscave/sono-redux-counter/2#-LIv40ZF3VEQwbhkotpc:-LIv40ZF3VEQwbhkotpd:b-mz3ycw) ([raw file](https://github.com/tigerscave/sono-redux-counter/blob/5dfeb0804dee5ea995a7000b98a2c2023bc5efd5/src/redux/createStore.js#L8)):*
> ```JavaScript
>   reducers,
>   {},
>   composeWithDevTools(),
> ```

you didn't compose anything.
you should use `devToolsEnhancer`

did you read this official document?
https://github.com/zalmoxisus/redux-devtools-extension#13-use-redux-devtools-extension-package-from-npm

**Review by sonokougg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tigerscave/sono-redux-counter/2)* status: 11 of 14 files reviewed, 3 unresolved discussions (waiting on @zigen and @sonokou1109)

___
*[src/index.js, line 19 at r2](https://reviewable.io/reviews/tigerscave/sono-redux-counter/2#-LIv3AtQ3oaaEhPLvim7:-LIwx-YR4HBWA8umbNbg:b1cznjb) ([raw file](https://github.com/tigerscave/sono-redux-counter/blob/5dfeb0804dee5ea995a7000b98a2c2023bc5efd5/src/index.js#L19)):*
<details><summary><i>Previously, zigen (zigen) wrote…</i></summary><blockquote>

what's this? do you really need this?
</blockquote></details>

I removed it.
___
*[src/registerServiceWorker.js, line 1 at r2](https://reviewable.io/reviews/tigerscave/sono-redux-counter/2#-LIv3Gpy6tfdA24nZKpX:-LIwxGQY4QYvqg-rXTMW:b-ynwl21) ([raw file](https://github.com/tigerscave/sono-redux-counter/blob/5dfeb0804dee5ea995a7000b98a2c2023bc5efd5/src/registerServiceWorker.js#L1)):*
<details><summary><i>Previously, zigen (zigen) wrote…</i></summary><blockquote>

do you use this file?
It's better to delete this needless file rather than put `eslint-disable`, 
</blockquote></details>

I removed it.
___
*[src/redux/createStore.js, line 8 at r2](https://reviewable.io/reviews/tigerscave/sono-redux-counter/2#-LIv40ZF3VEQwbhkotpc:-LIwxIaj2SNfBA1BQziP:bb7f2mf) ([raw file](https://github.com/tigerscave/sono-redux-counter/blob/5dfeb0804dee5ea995a7000b98a2c2023bc5efd5/src/redux/createStore.js#L8)):*
<details><summary><i>Previously, zigen (zigen) wrote…</i></summary><blockquote>

you didn't compose anything.
you should use `devToolsEnhancer`

did you read this official document?
https://github.com/zalmoxisus/redux-devtools-extension#13-use-redux-devtools-extension-package-from-npm
</blockquote></details>

done

**Review by zigen — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/tigerscave/sono-redux-counter/2)* status: all files reviewed, 2 unresolved discussions (waiting on @sonokou1109)

___
*[src/redux/createStore.js, line 8 at r3](https://reviewable.io/reviews/tigerscave/sono-redux-counter/2#-LIwy0eS2u6VUmVRERQl:-LIwy0eS2u6VUmVRERQm:b-uw5d6w) ([raw file](https://github.com/tigerscave/sono-redux-counter/blob/79b2dfe883c02ad011f98d7e1966ef901a726d24/src/redux/createStore.js#L8)):*
> ```JavaScript
>   reducers,
>   {},
>   /* preloadedState, */
> ```

if you want to denote that this 2nd argument is `preloadedState`,
you can put comment above what you point or assign `{}` to the variable which is named `preloadedState`
___
*[src/redux/createStore.js, line 10 at r3](https://reviewable.io/reviews/tigerscave/sono-redux-counter/2#-LIwxuGsDgXtRMJDnu0P:-LIwxuGsDgXtRMJDnu0Q:b-vxevb8) ([raw file](https://github.com/tigerscave/sono-redux-counter/blob/79b2dfe883c02ad011f98d7e1966ef901a726d24/src/redux/createStore.js#L10)):*
> ```JavaScript
>   /* preloadedState, */
>   devToolsEnhancer(
>   // Specify name here, actionsBlacklist, actionsCreators and other options if needed
> ```

do you really need this comment?

**Review by sonokougg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tigerscave/sono-redux-counter/2)* status: 13 of 14 files reviewed, 2 unresolved discussions (waiting on @zigen and @sonokou1109)

___
*[src/redux/createStore.js, line 8 at r3](https://reviewable.io/reviews/tigerscave/sono-redux-counter/2#-LIwy0eS2u6VUmVRERQl:-LIx-ULv2dZrPetgAKOW:batoqqr) ([raw file](https://github.com/tigerscave/sono-redux-counter/blob/79b2dfe883c02ad011f98d7e1966ef901a726d24/src/redux/createStore.js#L8)):*
<details><summary><i>Previously, zigen (zigen) wrote…</i></summary><blockquote>

if you want to denote that this 2nd argument is `preloadedState`,
you can put comment above what you point or assign `{}` to the variable which is named `preloadedState`
</blockquote></details>

I removed comment
___
*[src/redux/createStore.js, line 10 at r3](https://reviewable.io/reviews/tigerscave/sono-redux-counter/2#-LIwxuGsDgXtRMJDnu0P:-LIx-WYA5P4mf8yEM4uZ:batoqqr) ([raw file](https://github.com/tigerscave/sono-redux-counter/blob/79b2dfe883c02ad011f98d7e1966ef901a726d24/src/redux/createStore.js#L10)):*
<details><summary><i>Previously, zigen (zigen) wrote…</i></summary><blockquote>

do you really need this comment?
</blockquote></details>

I removed comment

**Review by zigen — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/tigerscave/sono-redux-counter/2)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
